### ISSUE TITLE
Create tests and Storybook

### ISSUE THREAD

**Issue by KapeNegra** [devflowinc/trieve-instantsearch-adapter#2]
We want to add a `stories/<framework_name>/` and a `tests/<framework_name>` folder to the adapter so we can showcase the components and also run automated tests.

For the `stories/` we want to add all the components, and add notes about the gaps/differences on each of the component sections.

For the automated tests we can go lighter and just test the minimal to make sure the component is working properly, and the changes we make to the adapter are working fine. 

We will focus on vanilla js and react for being the most popular framework, aiming to cover angular and vue as well.

**Comment by skeptrunedev** [comment]
Vanilla and React are great starting points 🔥

**Comment by Delacrobix** [comment]
The Storybook for React has been created, and work is already being done with the Instantsearch widgets. The next one to reach this same state will be the Storybook for vanilla JS. All Storybooks will be in the `stories` folder, and new folders will be created for each of the Storybooks for the different JS libraries.

Attached some evidences:

![story (1)](https://github.com/user-attachments/assets/e61a5ceb-7675-4f62-9b70-3e7eb95c7bff)

**Comment by Delacrobix** [comment]
Along the way, I encountered a problem with the existing Storybooks from Instantsearch. The Storybooks for vanilla [JS](https://github.com/algolia/instantsearch/tree/master/packages/instantsearch.js) and [VUE](https://github.com/algolia/instantsearch/tree/master/packages/vue-instantsearch) use older versions of Storybook with deprecated features. In the case of the Storybooks for [React](https://github.com/algolia/react-instantsearch) and [Angular](https://github.com/algolia/angular-instantsearch/tree/master/examples/storybook), they have been abandoned and not updated for years. For these reasons, it was decided to use [Storybook 8](https://storybook.js.org/docs) for all the Storybooks, taking inspiration from the [vanilla JS Storybook](https://instantsearchjs.netlify.app/stories/js/?path=/story/metadata-analytics--default) published by Instantsearch, which is available to the public.
